// ─── Clinic Templates: Pre-built phrase libraries for clinical note building ──

export const CLINIC_TEMPLATES = {
  'chest-pain': {
    name: 'Chest Pain Evaluation',
    hpi: [
      'Patient presents with substernal chest pain',
      'Pain radiates to left arm',
      'Exertional in nature',
      'Relieved by rest and nitroglycerin',
      'Associated with diaphoresis',
      'Sudden onset',
      'Crushing/pressure quality',
      'Duration > 20 minutes',
    ],
    ros: [
      'Denies shortness of breath',
      'Denies nausea or vomiting',
      'Denies palpitations',
      'Denies syncope',
      'Denies leg swelling',
    ],
    exam: [
      'BP 140/90, HR 92, RR 16, O2 98%',
      'Cardiac: Regular rate and rhythm, no murmurs',
      'Lungs: Clear to auscultation bilaterally',
      'Extremities: No edema or cyanosis',
      'JVP not elevated',
    ],
    assessment: [
      'Acute coronary syndrome — rule out',
      'Chest pain of unclear etiology',
      'Hypertension',
      'NSTEMI — possible',
    ],
    plan: [
      'ECG performed',
      'Troponin level ordered (serial)',
      'Aspirin 325 mg given',
      'Monitor on telemetry',
      'Cardiology consult recommended',
      'Chest X-ray ordered',
      'IV access established',
    ],
  },
  dyspnea: {
    name: 'Dyspnea Evaluation',
    hpi: [
      'Patient presents with acute shortness of breath',
      'Onset over last 2 hours',
      'Associated with chest discomfort',
      'Worsened with exertion',
      'Orthopnea present',
      'PND reported',
      'Gradual onset over days',
    ],
    ros: [
      'Denies fever',
      'Denies chills',
      'Denies leg pain or swelling',
      'Denies hemoptysis',
      'Reports productive cough',
    ],
    exam: [
      'BP 130/85, HR 105, RR 24, O2 sat 94%',
      'Lungs: Bilateral crackles',
      'Lungs: Clear to auscultation',
      'Cardiac: Tachycardia, regular rhythm',
      'Extremities: Bilateral pitting edema',
      'Extremities: No calf tenderness',
    ],
    assessment: [
      'Shortness of breath — etiology unclear',
      'Differential: PE, pneumonia, heart failure',
      'Tachycardia and tachypnea',
      'COPD exacerbation',
    ],
    plan: [
      'Chest X-ray ordered',
      'D-dimer sent',
      'ECG performed',
      'Oxygen supplementation via NC',
      'IV access established',
      'ABG ordered',
      'Diuretics if volume overload',
    ],
  },
  'abdominal-pain': {
    name: 'Abdominal Pain Evaluation',
    hpi: [
      'Patient presents with abdominal pain',
      'Localized to RLQ',
      'Localized to epigastric area',
      'Diffuse, poorly localized',
      'Associated with nausea/vomiting',
      'Associated with diarrhea',
      'No BM for 3 days',
      'Pain radiates to back',
      'Onset after meals',
    ],
    ros: [
      'Denies fever',
      'Denies melena or hematochezia',
      'Denies dysuria',
      'Denies vaginal bleeding',
      'Reports decreased appetite',
    ],
    exam: [
      'BP 125/80, HR 88, RR 18, Temp 37.2°C',
      'Abdomen: Soft, tender in RLQ',
      'Abdomen: Guarding present',
      'Abdomen: Rebound tenderness positive',
      'Abdomen: No distension',
      'Bowel sounds: Normal',
      'Bowel sounds: Absent',
      'Murphy sign positive',
    ],
    assessment: [
      'Acute appendicitis — rule out',
      'Biliary colic',
      'Bowel obstruction — rule out',
      'Gastroenteritis',
      'Peptic ulcer disease',
    ],
    plan: [
      'CBC, BMP, lipase ordered',
      'CT abdomen/pelvis ordered',
      'Ultrasound abdomen ordered',
      'NPO status',
      'IV fluids initiated',
      'Surgical consult',
      'Pain management: paracetamol',
    ],
  },
  generic: {
    name: 'Generic Clinical Note',
    hpi: [
      'Patient presents with chief complaint of',
      'Onset: acute / gradual',
      'Duration:',
      'Severity: mild / moderate / severe',
      'Aggravating factors:',
      'Relieving factors:',
    ],
    ros: [
      'Constitutional: No fever, chills, weight loss',
      'CV: No chest pain, palpitations',
      'Respiratory: No SOB, cough',
      'GI: No nausea, vomiting, diarrhea',
      'GU: No dysuria, hematuria',
      'MSK: No joint pain, swelling',
      'Neuro: No headache, dizziness, weakness',
    ],
    exam: [
      'General: Alert, oriented, no acute distress',
      'HEENT: Normocephalic, PERRL, moist mucosa',
      'Neck: Supple, no JVD, no lymphadenopathy',
      'Cardiac: Regular rate and rhythm, no murmurs',
      'Lungs: Clear to auscultation bilaterally',
      'Abdomen: Soft, non-tender, non-distended',
      'Extremities: No edema, no cyanosis',
      'Neuro: GCS 15, cranial nerves intact',
    ],
    assessment: [],
    plan: [],
  },
};

export const TEMPLATE_KEYS = Object.keys(CLINIC_TEMPLATES);
