import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatDate, formatDateTime } from '../utils/formatters';

const exportService = {
  generateDailySummary(patient, labs = [], meds = [], notes = []) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('MEDICAL DAILY SUMMARY', pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by MedWard Pro — Educational Use Only', pageWidth / 2, 27, { align: 'center' });

    // Patient Sticker Area
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.rect(14, 32, pageWidth - 28, 30);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`Name: ${patient.name || ''}`, 18, 40);
    doc.text(`File #: ${patient.fileNumber || 'N/A'}`, 18, 47);
    doc.text(`Age/Sex: ${patient.ageSex || ''}`, pageWidth / 2, 40);
    doc.text(`Ward: ${patient.ward || ''}`, pageWidth / 2, 47);
    doc.text(`Date: ${formatDate(new Date())}`, 18, 54);
    doc.text(`Status: ${patient.currentStatus || ''}`, pageWidth / 2, 54);

    let yPos = 70;

    // Diagnosis
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Diagnosis', 14, yPos);
    yPos += 6;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(patient.diagnosis || 'Not specified', 14, yPos);
    yPos += 10;

    // Vitals
    if (patient.lastVitals) {
      doc.setFont('helvetica', 'bold');
      doc.text('Latest Vitals', 14, yPos);
      yPos += 6;
      doc.setFont('helvetica', 'normal');
      const v = patient.lastVitals;
      doc.text(`BP: ${v.bp || '—'} | HR: ${v.hr || '—'} | RR: ${v.rr || '—'} | Temp: ${v.temp || '—'}°C | SpO2: ${v.spo2 || '—'}% ${v.o2Delivery || ''}`, 14, yPos);
      yPos += 10;
    }

    // Active Medications Table
    if (meds.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Active Medications', 14, yPos);
      yPos += 4;

      doc.autoTable({
        startY: yPos,
        head: [['Medication', 'Dose', 'Route', 'Frequency']],
        body: meds.map((m) => [m.name, m.dose, m.route, m.frequency]),
        theme: 'grid',
        styles: { fontSize: 9 },
        headStyles: { fillColor: [30, 58, 95] },
        margin: { left: 14, right: 14 },
      });
      yPos = doc.lastAutoTable.finalY + 10;
    }

    // Recent Labs Table
    if (labs.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Recent Lab Results', 14, yPos);
      yPos += 4;

      doc.autoTable({
        startY: yPos,
        head: [['Test', 'Value', 'Unit', 'Status', 'Trend']],
        body: labs.slice(0, 15).map((l) => [
          l.testName,
          l.value,
          l.unit || '',
          l.isCritical ? 'CRITICAL' : l.isAbnormal ? 'Abnormal' : 'Normal',
          l.trend || '—',
        ]),
        theme: 'grid',
        styles: { fontSize: 9 },
        headStyles: { fillColor: [30, 58, 95] },
        margin: { left: 14, right: 14 },
      });
      yPos = doc.lastAutoTable.finalY + 10;
    }

    // Active Alerts
    if (patient.activeAlerts?.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Active Alerts', 14, yPos);
      yPos += 6;
      doc.setFont('helvetica', 'normal');
      patient.activeAlerts.forEach((alert) => {
        doc.text(`• ${alert}`, 18, yPos);
        yPos += 5;
      });
      yPos += 5;
    }

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Generated by MedWard Pro — Educational Use Only — ${formatDateTime(new Date())}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );

    // Trigger download
    doc.save(`MedWard_${patient.name?.replace(/\s+/g, '_') || 'patient'}_${formatDate(new Date())}.pdf`);
  },
};

export default exportService;
