import type { Timestamp } from 'firebase/firestore'

export type TaskPriority = 'critical' | 'high' | 'medium' | 'low'
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled'
export type TaskCategory = 'medication' | 'lab' | 'imaging' | 'consult' | 'procedure' | 'nursing' | 'discharge' | 'other'
export type EscalationLevel = 'none' | 'warning' | 'overdue' | 'critical'
export type CompletionProofType = 'note' | 'image' | 'signature' | 'timestamp'
export type TaskGenerationSource = 'problem' | 'order_set' | 'protocol' | 'manual'

export interface Task {
  id: string
  patientId: string
  patientName: string
  bedNumber: string
  title: string
  description: string
  category: TaskCategory
  priority: TaskPriority
  status: TaskStatus
  assignedTo: string
  assignedToName: string
  createdBy: string
  createdByName: string
  dueAt?: Timestamp
  completedAt?: Timestamp
  autoDeleteAt?: Timestamp
  completedBy?: string
  notes?: string
  recurring?: {
    frequency: 'once' | 'daily' | 'bid' | 'tid' | 'qid' | 'q4h' | 'q6h' | 'q8h' | 'q12h'
    endDate?: Timestamp
  }
  createdAt: Timestamp
  updatedAt: Timestamp

  // NEW (Phase 0.2): Closed-loop tasking - Acknowledgment
  acknowledgedAt?: Timestamp
  acknowledgedBy?: string
  viewedBy: string[]

  // NEW (Phase 0.2): Completion proof tracking
  completionProof?: {
    type: CompletionProofType
    content: string
  }

  // NEW (Phase 0.2): Auto-generation metadata
  generatedFrom?: {
    type: TaskGenerationSource
    sourceId: string
    autoGenerated: boolean
  }

  // NEW (Phase 0.2): Escalation tracking
  escalationLevel: EscalationLevel
  escalatedTo?: string
  escalatedAt?: Timestamp
  overdueAlertSentAt?: Timestamp
}

export interface TaskFormData {
  patientId: string
  title: string
  description: string
  category: TaskCategory
  priority: TaskPriority
  assignedTo: string
  dueAt?: string
  recurring?: {
    frequency: 'once' | 'daily' | 'bid' | 'tid' | 'qid' | 'q4h' | 'q6h' | 'q8h' | 'q12h'
    endDate?: string
  }
  notes?: string
}
