/**
 * Complaint-Based Clerking Templates
 * Guided assessment templates for common presenting complaints
 * Based on UK clinical practice and NICE guidelines
 */

export interface ComplaintTemplate {
  id: string
  complaint: string
  category: string
  promptFields: string[] // Guided questions for history taking
  suggestedExams: string[] // Examination areas to focus on
  redFlags: string[] // Things that must not be missed
  suggestedInvestigations: string[] // Initial workup
  differentials: string[] // Common differentials to consider
}

export const COMPLAINT_TEMPLATES: ComplaintTemplate[] = [
  {
    id: 'chest-pain',
    complaint: 'Chest Pain',
    category: 'Acute Presentation',
    promptFields: [
      'Site of pain (localization)?',
      'Onset (sudden vs gradual)?',
      'Character (sharp, dull, pressure, pleuritic)?',
      'Radiation (arm, jaw, back)?',
      'Associated symptoms (SOB, sweating, nausea)?',
      'Severity (0-10 scale)?',
      'Exacerbating factors (movement, position)?',
      'Time since onset?',
    ],
    suggestedExams: [
      'General appearance (distress level)',
      'Cardiovascular (BP both arms, HR, murmurs, JVP)',
      'Respiratory (rate, SpO2, lung crackles)',
      'Palpation (reproducible tenderness, focal pain)',
    ],
    redFlags: [
      'Acute coronary syndrome (STEMI/NSTEMI)',
      'Aortic dissection (sudden severe, tearing)',
      'Pulmonary embolism (SOB, hypoxia)',
      'Pneumothorax (collapsed lung)',
      'Tamponade (muffled heart sounds, hypotension)',
      'Oesophageal rupture (Boerhaave syndrome)',
    ],
    suggestedInvestigations: [
      'ECG (STAT)',
      'High-sensitivity troponin (0h and 3h)',
      'CXR (PA and lateral)',
      'FBC, U&Es, LFTs',
      'D-dimer (if PE suspected)',
      'CT pulmonary angiography (if PE suspected)',
    ],
    differentials: [
      'Acute coronary syndrome',
      'Pulmonary embolism',
      'Aortic dissection',
      'Pneumonia',
      'Pleural effusion',
      'Musculoskeletal pain',
      'GORD',
      'Pericarditis',
    ],
  },

  {
    id: 'shortness-of-breath',
    complaint: 'Shortness of Breath',
    category: 'Acute Presentation',
    promptFields: [
      'Onset (sudden vs gradual)?',
      'Severity (at rest vs exertional)?',
      'Associated chest pain?',
      'Cough present? (productive vs dry)',
      'Orthopnoea? (how many pillows)',
      'Paroxysmal nocturnal dyspnoea?',
      'Recent trauma or immobility?',
      'Leg swelling?',
    ],
    suggestedExams: [
      'Respiratory rate and effort',
      'Oxygen saturation (room air and on O2)',
      'Accessory muscle use',
      'Lung auscultation (crackles, wheezes, silent areas)',
      'Heart sounds (murmur, gallop, JVP)',
      'Leg examination (DVT signs)',
      'Abdomen (ascites, hepatomegaly)',
    ],
    redFlags: [
      'Stridor (upper airway obstruction)',
      'Hypoxia refractory to O2',
      'Tachycardia >120',
      'Hypotension',
      'Signs of sepsis',
      'Respiratory distress requiring intubation',
    ],
    suggestedInvestigations: [
      'ABG/VBG (pH, pO2, pCO2, lactate)',
      'CXR (infiltrates, effusion, PTX)',
      'ECG (signs of PE or MI)',
      'BNP/NT-proBNP (heart failure)',
      'D-dimer (if PE suspected)',
      'CT pulmonary angiography (if PE likely)',
      'FBC, U&Es, CRP',
    ],
    differentials: [
      'Pneumonia',
      'Pulmonary embolism',
      'Asthma/COPD exacerbation',
      'Heart failure',
      'Pneumothorax',
      'Pleural effusion',
      'Anaphylaxis',
      'Anxiety',
    ],
  },

  {
    id: 'abdominal-pain',
    complaint: 'Abdominal Pain',
    category: 'Acute Presentation',
    promptFields: [
      'Site of pain (localize on abdomen)?',
      'Onset (sudden vs insidious)?',
      'Character (sharp, colicky, dull)?',
      'Severity (0-10 scale)?',
      'Associated nausea/vomiting?',
      'Bowel movements (diarrhoea, constipation)?',
      'Last meal when?',
      'Fever present?',
      'Radiation of pain?',
    ],
    suggestedExams: [
      'Inspection (distension, visible peristalsis)',
      'Palpation (guarding, rigidity, rebound tenderness)',
      'Percussion (hyperresonance, dullness)',
      'Auscultation (bowel sounds)',
      'Rectal examination (if appropriate)',
      'Costovertebral angle tenderness',
      'Rovsing sign, Murphy sign (if appendicitis/cholecystitis)',
    ],
    redFlags: [
      'Peritonism (guarding, rigidity, rebound)',
      'Shock (hypotension, tachycardia)',
      'Uncontrolled vomiting',
      'Acute severe pancreatitis (epigastric pain, elevated amylase)',
      'Ruptured AAA (back pain, hypotension)',
      'Perforated viscus (free air on imaging)',
    ],
    suggestedInvestigations: [
      'FBC (WCC elevation)',
      'CRP (inflammation)',
      'U&Es (electrolytes, creatinine)',
      'LFTs (bilirubin if biliary)',
      'Amylase/lipase (pancreatitis)',
      'Urine dipstick (exclude UTI)',
      'Abdominal X-ray (obstruction signs)',
      'CT abdomen/pelvis (if not clear)',
    ],
    differentials: [
      'Acute appendicitis',
      'Cholecystitis/choledocholithiasis',
      'Peptic ulcer disease',
      'Pancreatitis',
      'Small bowel obstruction',
      'Inflammatory bowel disease',
      'Gastroenteritis',
      'Mesenteric ischaemia',
    ],
  },

  {
    id: 'headache',
    complaint: 'Headache',
    category: 'Acute Presentation',
    promptFields: [
      'Onset (sudden vs gradual)?',
      'Location (localized vs diffuse)?',
      'Character (throbbing, pressure, sharp)?',
      'Severity (0-10 scale)?',
      'Associated neck stiffness?',
      'Photophobia or phonophobia?',
      'Visual changes?',
      'Neurological symptoms?',
      'Fever present?',
      'Recent head trauma?',
    ],
    suggestedExams: [
      'General (fever, rash)',
      'Neurological assessment (cranial nerves, power, sensation)',
      'Meningeal signs (neck stiffness, Kernig sign)',
      'Fundoscopy (papilloedema)',
      'Blood pressure (hypertensive emergency)',
      'Glasgow Coma Scale',
    ],
    redFlags: [
      'Thunderclap onset (subarachnoid haemorrhage)',
      'Meningism (fever + neck stiffness)',
      'Focal neurological signs (stroke)',
      'Papilloedema (raised intracranial pressure)',
      'Reduced consciousness',
      'First severe headache of life',
    ],
    suggestedInvestigations: [
      'CT head non-contrast (SAH, ICH, mass)',
      'Lumbar puncture (meningitis - if CT normal)',
      'Blood cultures (meningitis)',
      'U&Es (electrolytes)',
      'Glucose (hypoglycaemia)',
    ],
    differentials: [
      'Subarachnoid haemorrhage',
      'Meningitis',
      'Encephalitis',
      'Acute stroke',
      'Tension headache',
      'Migraine',
      'Sinusitis',
      'Idiopathic intracranial hypertension',
    ],
  },

  {
    id: 'falls-collapse',
    complaint: 'Falls / Collapse',
    category: 'Acute Presentation',
    promptFields: [
      'Mechanical fall vs collapse?',
      'Witness account of event?',
      'Loss of consciousness?',
      'Tongue biting or incontinence? (seizure)',
      'Palpitations before event?',
      'Chest pain?',
      'Recent head trauma?',
      'Medications taken?',
      'Alcohol consumption?',
    ],
    suggestedExams: [
      'Full neurological examination',
      'Cardiovascular exam (BP lying and standing, arrhythmias)',
      'Fundoscopy (retinal changes)',
      'Assessment for injuries',
      'Cranial nerve examination',
      'Motor and sensory testing',
    ],
    redFlags: [
      'Head injury (GCS <15, pupil changes)',
      'Arrhythmia (abnormal pulse)',
      'Hypotension',
      'Seizure activity',
      'Stroke signs (facial droop, arm weakness)',
    ],
    suggestedInvestigations: [
      'ECG (arrhythmias, MI)',
      'Blood glucose (hypoglycaemia)',
      'FBC, U&Es (anaemia, electrolytes)',
      'CT head (if head injury or neuro signs)',
      '24-hour BP monitoring (orthostatic hypotension)',
      'Holter monitor (paroxysmal arrhythmia)',
    ],
    differentials: [
      'Syncope (vasovagal, cardiac)',
      'Seizure',
      'Arrhythmia',
      'Stroke/TIA',
      'Orthostatic hypotension',
      'Hypoglycaemia',
      'Mechanical fall',
      'Medication side effect',
    ],
  },

  {
    id: 'confusion-delirium',
    complaint: 'Confusion / Delirium',
    category: 'Acute Presentation',
    promptFields: [
      'Acute onset vs insidious?',
      'Fluctuating symptoms?',
      'Known triggers (infection, drugs)?',
      'Recent medication changes?',
      'Fever?',
      'Urinary symptoms?',
      'Respiratory symptoms?',
      'Recent surgery or trauma?',
      'Baseline cognition?',
    ],
    suggestedExams: [
      'Abbreviated Mental Test (AMT4)',
      'Glasgow Coma Scale',
      'Full neurological examination',
      'Cardiovascular (BP, HR, signs of sepsis)',
      'Respiratory (signs of infection)',
      'Abdomen (signs of infection)',
      'Skin (rash, signs of infection)',
    ],
    redFlags: [
      'New focal neurological signs (stroke)',
      'Fever + neck stiffness (meningitis)',
      'Signs of sepsis',
      'Hypoxia',
      'Hypoglycaemia',
      'Reduced consciousness (GCS <10)',
    ],
    suggestedInvestigations: [
      'FBC (infection, anaemia)',
      'U&Es (Na+, K+, Cr)',
      'Glucose (hypoglycaemia)',
      'CRP (infection)',
      'Urine dipstick and culture (UTI)',
      'Blood cultures (sepsis)',
      'ECG (arrhythmia)',
      'CT head (if focal signs or trauma)',
      'Chest X-ray (pneumonia)',
    ],
    differentials: [
      'Infection (UTI, pneumonia, sepsis)',
      'Hypoglycaemia',
      'Medications (opioids, benzodiazepines)',
      'Acute stroke',
      'Meningitis/encephalitis',
      'Hypoxia',
      'Metabolic (hyponatraemia, hepatic encephalopathy)',
    ],
  },

  {
    id: 'fever-sepsis',
    complaint: 'Fever / Sepsis',
    category: 'Acute Presentation',
    promptFields: [
      'Temperature measured?',
      'Onset (acute vs gradual)?',
      'Source identification?',
      'Recent travel or sick contacts?',
      'Symptoms by system (respiratory, abdominal)?',
      'Rash present?',
      'Recent surgery or invasive procedures?',
      'Immunosuppression?',
    ],
    suggestedExams: [
      'General appearance (distress level)',
      'Cardiovascular (BP, HR, cap refill)',
      'Respiratory (RR, SpO2, lung auscultation)',
      'Abdomen (tenderness, peritonism)',
      'Skin (rash, signs of infection)',
      'Neurological (meningeal signs)',
    ],
    redFlags: [
      'Sepsis criteria (fever + 2 SIRS)',
      'Hypotension or lactate >2',
      'Altered mental status',
      'Petechial rash (meningococcaemia)',
      'Rash + fever + neck stiffness (meningitis)',
    ],
    suggestedInvestigations: [
      'Blood cultures (2 sets) before antibiotics',
      'FBC (WCC)',
      'CRP/procalcitonin (inflammation)',
      'U&Es, LFTs, glucose',
      'Lactate (tissue perfusion)',
      'Urinalysis and culture (UTI)',
      'Chest X-ray (pneumonia)',
      'Abdominal imaging if indicated',
    ],
    differentials: [
      'Bacterial sepsis',
      'Viral illness',
      'Urinary tract infection',
      'Pneumonia',
      'Intra-abdominal infection',
      'Meningitis',
      'Endocarditis',
      'Malaria or other parasites',
    ],
  },

  {
    id: 'palpitations',
    complaint: 'Palpitations',
    category: 'Acute Presentation',
    promptFields: [
      'Onset (sudden vs gradual)?',
      'Duration (seconds, minutes, hours)?',
      'Regular or irregular rhythm?',
      'Associated chest pain?',
      'Associated SOB?',
      'Dizziness or syncope?',
      'Recent caffeine or stimulant use?',
      'Stress or anxiety?',
    ],
    suggestedExams: [
      'Pulse (rate and regularity)',
      'Blood pressure',
      'Cardiovascular examination',
      'Respiratory examination',
      'Signs of thyroid disease',
    ],
    redFlags: [
      'Haemodynamic instability (hypotension, syncope)',
      'Severe chest pain',
      'Signs of heart failure (pulmonary crackles)',
      'Severe tachycardia (>150)',
    ],
    suggestedInvestigations: [
      'ECG (STAT)',
      'Troponin (MI)',
      'Thyroid function tests (hyperthyroidism)',
      'Electrolytes (K+, Ca2+, Mg2+)',
      'FBC (anaemia)',
      '24-hour Holter monitor (paroxysmal arrhythmia)',
      'Echocardiogram (structural heart disease)',
    ],
    differentials: [
      'Atrial fibrillation',
      'Supraventricular tachycardia',
      'Ventricular ectopics',
      'Acute coronary syndrome',
      'Thyrotoxicosis',
      'Anaemia',
      'Anxiety',
      'Caffeine sensitivity',
    ],
  },

  {
    id: 'leg-swelling',
    complaint: 'Leg Swelling',
    category: 'Acute Presentation',
    promptFields: [
      'Unilateral or bilateral?',
      'Onset (acute vs gradual)?',
      'Recent immobility (long flight, bed rest)?',
      'Recent surgery or trauma?',
      'Calf pain or warmth?',
      'Shortness of breath (PE)?',
      'Colour changes?',
      'Associated abdominal swelling?',
    ],
    suggestedExams: [
      'Compare both legs (circumference, colour)',
      'Palpate for calf tenderness',
      'Check for Homan sign',
      'Assess for skin changes (erythema, warmth)',
      'Check for pitting oedema',
      'Abdominal examination (hepatomegaly, ascites)',
    ],
    redFlags: [
      'Signs of DVT (unilateral swelling, warmth, pain)',
      'Symptoms of PE (SOB, chest pain, tachycardia)',
      'Signs of cellulitis (erythema, warmth, fever)',
      'Compartment syndrome (severe pain, sensory changes)',
    ],
    suggestedInvestigations: [
      'Bilateral leg ultrasound/Doppler (DVT)',
      'D-dimer (if DVT suspected)',
      'CT pulmonary angiography (if PE suspected)',
      'FBC, U&Es, LFTs (systemic causes)',
      'Albumin (nephrotic syndrome)',
    ],
    differentials: [
      'Deep vein thrombosis',
      'Cellulitis',
      'Lymphoedema',
      'Nephrotic syndrome',
      'Liver disease (ascites)',
      'Heart failure',
      'Musculoskeletal injury',
      'Venous insufficiency',
    ],
  },

  {
    id: 'back-pain',
    complaint: 'Back Pain',
    category: 'Acute Presentation',
    promptFields: [
      'Onset (sudden vs gradual)?',
      'Location (lower back, midline)?',
      'Radiation down leg (radiculopathy)?',
      'Associated lower limb neurological symptoms?',
      'Numbness in saddle area (cauda equina)?',
      'Recent trauma?',
      'Weight loss or fever?',
      'Bowel/bladder dysfunction?',
    ],
    suggestedExams: [
      'Palpate spine (tenderness, step-off)',
      'Straight leg raise test',
      'Lower limb neurology (power, sensation, reflexes)',
      'Perianal sensation (cauda equina)',
      'Rectal tone (cauda equina)',
      'Abdominal examination (AAA)',
    ],
    redFlags: [
      'Cauda equina syndrome (bilateral leg pain, saddle anaesthesia, urinary retention)',
      'Severe unilateral neurological deficit',
      'Signs of infection (fever, spinal tenderness)',
      'Signs of AAA (hypotension, pulsatile mass, back pain)',
      'Spinal fracture (trauma, osteoporosis, malignancy)',
    ],
    suggestedInvestigations: [
      'MRI lumbar spine (cauda equina, disc herniation)',
      'CT if trauma (fracture)',
      'FBC, CRP (infection)',
      'X-ray if DEXA osteoporotic bone',
      'CT abdomen (AAA)',
    ],
    differentials: [
      'Lumbar strain',
      'Disc herniation/radiculopathy',
      'Spinal stenosis',
      'Cauda equina syndrome',
      'Spinal infection',
      'Metastatic disease',
      'Aortic aneurysm',
      'Pyelonephritis',
    ],
  },
]
