// ─── Clinical Mode Definitions ───────────────────────────────────────────────
export const MODES = {
  WARD: 'ward',
  EMERGENCY: 'emergency',
  CLINIC: 'clinic',
};

export const MODE_META = {
  [MODES.WARD]: {
    label: 'Ward',
    shortLabel: 'W',
    description: 'Inpatient ward management',
    color: 'trust-blue',
    bgClass: 'bg-blue-50',
    textClass: 'text-blue-700',
    borderClass: 'border-blue-200',
    badgeBg: 'bg-blue-100',
  },
  [MODES.EMERGENCY]: {
    label: 'Emergency',
    shortLabel: 'E',
    description: 'Emergency protocols & rapid response',
    color: 'critical-red',
    bgClass: 'bg-red-50',
    textClass: 'text-red-700',
    borderClass: 'border-red-200',
    badgeBg: 'bg-red-100',
  },
  [MODES.CLINIC]: {
    label: 'Clinic',
    shortLabel: 'C',
    description: 'Outpatient clinic workflows',
    color: 'emerald',
    bgClass: 'bg-emerald-50',
    textClass: 'text-emerald-700',
    borderClass: 'border-emerald-200',
    badgeBg: 'bg-emerald-100',
  },
};

// ─── Mode Capabilities ──────────────────────────────────────────────────────
export const modeCapabilities = {
  [MODES.WARD]: {
    allowedComponents: [
      'PatientList', 'PatientDetail', 'LabPanel', 'MedPanel',
      'NotePanel', 'VitalsPanel', 'PlanPanel', 'SBARGenerator',
      'AuditPanel', 'DailySummary',
    ],
    allowedTools: [
      'askClinical', 'getAntibioticGuide', 'getDrugInfo',
      'analyzeLabImage', 'generateSBAR', 'analyzeTrendLabs',
    ],
  },
  [MODES.EMERGENCY]: {
    allowedComponents: [
      'PatientList', 'PatientDetail', 'LabPanel', 'MedPanel',
      'VitalsPanel', 'EmergencyToolGrid',
    ],
    allowedTools: [
      'getOnCallProtocol', 'askClinical', 'getDrugInfo',
      'getAntibioticGuide', 'analyzeLabImage',
    ],
  },
  [MODES.CLINIC]: {
    allowedComponents: [
      'PatientList', 'PatientDetail', 'LabPanel', 'MedPanel',
      'NotePanel', 'PlanPanel',
    ],
    allowedTools: [
      'askClinical', 'getDrugInfo', 'getAntibioticGuide',
      'analyzeTrendLabs',
    ],
  },
};

// ─── Mode Policies ───────────────────────────────────────────────────────────
export const modePolicies = {
  [MODES.WARD]: {
    confirmationRequired: ['stopMed', 'deleteLab'],
    phiWarning: true,
    offlineSupport: true,
  },
  [MODES.EMERGENCY]: {
    confirmationRequired: [],
    phiWarning: false,
    offlineSupport: true,
  },
  [MODES.CLINIC]: {
    confirmationRequired: ['stopMed', 'deleteLab', 'deleteNote'],
    phiWarning: true,
    offlineSupport: false,
  },
};

// ─── Clinical Tools Registry ─────────────────────────────────────────────────
export const clinicalTools = [
  {
    id: 'acls',
    label: 'ACLS Protocol',
    icon: 'Heart',
    category: 'emergency',
    severity: 'critical',
    appliesTo: [MODES.EMERGENCY],
    prompt: 'Walk me through ACLS protocol for this patient',
    requiresPatient: false,
    requiresLabs: false,
    timeSensitive: true,
  },
  {
    id: 'sepsis',
    label: 'Sepsis Bundle',
    icon: 'Thermometer',
    category: 'emergency',
    severity: 'critical',
    appliesTo: [MODES.EMERGENCY, MODES.WARD],
    prompt: 'Guide sepsis bundle: cultures, lactate, antibiotics, fluids',
    requiresPatient: false,
    requiresLabs: true,
    timeSensitive: true,
  },
  {
    id: 'dka',
    label: 'DKA Protocol',
    icon: 'Droplets',
    category: 'emergency',
    severity: 'urgent',
    appliesTo: [MODES.EMERGENCY, MODES.WARD],
    prompt: 'DKA management: insulin drip, fluids, potassium, monitoring',
    requiresPatient: false,
    requiresLabs: true,
    timeSensitive: true,
  },
  {
    id: 'aki',
    label: 'AKI Workup',
    icon: 'Activity',
    category: 'renal',
    severity: 'urgent',
    appliesTo: [MODES.WARD, MODES.EMERGENCY],
    prompt: 'AKI workup and management approach',
    requiresPatient: true,
    requiresLabs: true,
    timeSensitive: false,
  },
  {
    id: 'antibiotic',
    label: 'Antibiotic Guide',
    icon: 'Pill',
    category: 'infectious',
    severity: 'standard',
    appliesTo: [MODES.WARD, MODES.EMERGENCY, MODES.CLINIC],
    prompt: 'Recommend antibiotic therapy',
    requiresPatient: true,
    requiresLabs: false,
    timeSensitive: false,
  },
  {
    id: 'electrolyte',
    label: 'Electrolyte Correction',
    icon: 'Zap',
    category: 'metabolic',
    severity: 'urgent',
    appliesTo: [MODES.WARD, MODES.EMERGENCY],
    prompt: 'Electrolyte correction protocol (Na/K/Ca/Mg/PO4)',
    requiresPatient: true,
    requiresLabs: true,
    timeSensitive: false,
  },
  {
    id: 'transfusion',
    label: 'Transfusion Guide',
    icon: 'Droplet',
    category: 'hematology',
    severity: 'urgent',
    appliesTo: [MODES.WARD, MODES.EMERGENCY],
    prompt: 'Blood product transfusion guide and thresholds',
    requiresPatient: true,
    requiresLabs: true,
    timeSensitive: false,
  },
  {
    id: 'chest_pain',
    label: 'Chest Pain',
    icon: 'HeartPulse',
    category: 'emergency',
    severity: 'critical',
    appliesTo: [MODES.EMERGENCY],
    prompt: 'Acute chest pain workup: ECG, troponin, differentials',
    requiresPatient: false,
    requiresLabs: false,
    timeSensitive: true,
  },
  {
    id: 'stroke',
    label: 'Stroke Protocol',
    icon: 'Brain',
    category: 'emergency',
    severity: 'critical',
    appliesTo: [MODES.EMERGENCY],
    prompt: 'Acute stroke protocol: time window, imaging, thrombolysis criteria',
    requiresPatient: false,
    requiresLabs: false,
    timeSensitive: true,
  },
  {
    id: 'insulin',
    label: 'Insulin Dosing',
    icon: 'Syringe',
    category: 'endocrine',
    severity: 'standard',
    appliesTo: [MODES.WARD, MODES.CLINIC],
    prompt: 'Insulin dosing and adjustment for inpatient glucose management',
    requiresPatient: true,
    requiresLabs: true,
    timeSensitive: false,
  },
  {
    id: 'drug_info',
    label: 'Drug Info',
    icon: 'FileText',
    category: 'pharmacy',
    severity: 'standard',
    appliesTo: [MODES.WARD, MODES.EMERGENCY, MODES.CLINIC],
    prompt: 'Drug information lookup',
    requiresPatient: false,
    requiresLabs: false,
    timeSensitive: false,
  },
  {
    id: 'handover',
    label: 'SBAR Handover',
    icon: 'ClipboardList',
    category: 'communication',
    severity: 'standard',
    appliesTo: [MODES.WARD],
    prompt: 'Generate SBAR handover for this patient',
    requiresPatient: true,
    requiresLabs: false,
    timeSensitive: false,
  },
  {
    id: 'discharge',
    label: 'Discharge Plan',
    icon: 'LogOut',
    category: 'transitions',
    severity: 'standard',
    appliesTo: [MODES.WARD, MODES.CLINIC],
    prompt: 'Discharge planning checklist and medication reconciliation',
    requiresPatient: true,
    requiresLabs: false,
    timeSensitive: false,
  },
  {
    id: 'pain',
    label: 'Pain Protocol',
    icon: 'Shield',
    category: 'palliative',
    severity: 'standard',
    appliesTo: [MODES.WARD, MODES.EMERGENCY, MODES.CLINIC],
    prompt: 'Pain assessment and management protocol (WHO ladder)',
    requiresPatient: false,
    requiresLabs: false,
    timeSensitive: false,
  },
  {
    id: 'airway',
    label: 'Airway Management',
    icon: 'Wind',
    category: 'emergency',
    severity: 'critical',
    appliesTo: [MODES.EMERGENCY],
    prompt: 'Airway management: assessment, intubation, RSI drugs',
    requiresPatient: false,
    requiresLabs: false,
    timeSensitive: true,
  },
];

// ─── Get tools for a specific mode ──────────────────────────────────────────
export function getToolsForMode(mode) {
  return clinicalTools.filter((tool) => tool.appliesTo.includes(mode));
}
