/**
 * Order Set Templates (Phase 4)
 *
 * Pre-built order sets for common clinical scenarios
 * Based on UK clinical guidelines (NICE, BTS, RCP)
 */

import type { OrderSet } from '@/types/orderSet';

export const ORDER_SETS: OrderSet[] = [
  // 1. Chest Pain / ACS
  {
    id: 'chest-pain-acs',
    name: 'Chest Pain / ACS',
    category: 'cardiac',
    description: 'Acute coronary syndrome workup (NICE CG95)',
    icon: '💔',
    color: 'bg-red-500',
    items: [
      {
        id: '1',
        title: 'ECG (repeat if ongoing pain)',
        description: '12-lead ECG, repeat every 30 minutes if ongoing pain',
        category: 'other',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'High-sensitivity troponin (0h)',
        description: 'Baseline troponin',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'High-sensitivity troponin (3h)',
        description: 'Repeat troponin at 3 hours',
        category: 'lab',
        priority: 'critical',
        timing: '4hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Aspirin 300mg',
        description: 'Chewed, unless contraindicated',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '5',
        title: 'FBC, U&Es, glucose, lipids',
        description: 'Baseline bloods',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '6',
        title: 'CXR',
        description: 'Exclude other causes',
        category: 'imaging',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
      {
        id: '7',
        title: 'Cardiology review',
        description: 'Urgent if STEMI/NSTEMI confirmed',
        category: 'consult',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Contact if troponin positive or dynamic ECG changes',
      },
    ],
    estimatedDuration: '3-6 hours',
    clinicalGuideline: 'NICE CG95 - Chest Pain',
  },

  // 2. Sepsis Six
  {
    id: 'sepsis-six',
    name: 'Sepsis Six',
    category: 'infectious',
    description: 'Sepsis 6 bundle (Surviving Sepsis Campaign)',
    icon: '🦠',
    color: 'bg-purple-500',
    items: [
      {
        id: '1',
        title: 'High-flow oxygen (target 94-98%)',
        description: 'Oxygen therapy to maintain saturation',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Blood cultures (2 sets)',
        description: 'Before antibiotics if possible',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'IV antibiotics',
        description: 'Broad-spectrum within 1 hour (e.g., Tazocin 4.5g)',
        category: 'medication',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'IV fluid challenge',
        description: '500ml crystalloid if hypotensive',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '5',
        title: 'Lactate measurement',
        description: 'Serum lactate or VBG',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'Urine output monitoring',
        description: 'Catheterise if needed',
        category: 'nursing',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '7',
        title: 'FBC, U&Es, CRP',
        description: 'Baseline bloods',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '8',
        title: 'CXR',
        description: 'Source identification',
        category: 'imaging',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '1-2 hours (bundle completion)',
    clinicalGuideline: 'Surviving Sepsis Campaign',
  },

  // 3. DKA
  {
    id: 'dka-protocol',
    name: 'DKA Protocol',
    category: 'metabolic',
    description: 'Diabetic ketoacidosis management (JBDS)',
    icon: '💉',
    color: 'bg-orange-500',
    items: [
      {
        id: '1',
        title: 'Venous blood gas',
        description: 'pH, bicarbonate, ketones',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Capillary blood glucose',
        description: 'Baseline BM',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'IV fluids (0.9% saline)',
        description: '1L over 1 hour initially',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Fixed-rate insulin infusion',
        description: '0.1 units/kg/hr',
        category: 'medication',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '5',
        title: 'Hourly BMs + ketones',
        description: 'Continuous monitoring',
        category: 'nursing',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'U&Es (repeat 2-hourly)',
        description: 'Monitor potassium',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '7',
        title: 'ECG',
        description: 'Exclude cardiac complications',
        category: 'other',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '24+ hours',
    clinicalGuideline: 'JBDS DKA Guideline',
  },

  // 4. Hyperkalemia
  {
    id: 'hyperkalemia',
    name: 'Hyperkalemia',
    category: 'metabolic',
    description: 'Emergency hyperkalaemia management',
    icon: '⚡',
    color: 'bg-yellow-600',
    items: [
      {
        id: '1',
        title: 'ECG',
        description: 'Check for ECG changes (tall T waves, wide QRS)',
        category: 'other',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Calcium gluconate 10% IV',
        description: '10ml over 2-5 minutes if ECG changes',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Cardiac protection - give first if ECG changes',
      },
      {
        id: '3',
        title: 'Insulin-dextrose infusion',
        description: '10 units Actrapid in 50ml 50% dextrose over 15 mins',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Salbutamol nebuliser',
        description: '10-20mg nebulised',
        category: 'medication',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: false,
      },
      {
        id: '5',
        title: 'Recheck K+ in 1 hour',
        description: 'Monitor response to treatment',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'Stop nephrotoxic drugs',
        description: 'Review and stop ACEi, NSAIDs, spironolactone',
        category: 'medication',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '2-4 hours',
    clinicalGuideline: 'Resuscitation Council UK',
  },

  // 5. Stroke / CVA
  {
    id: 'stroke',
    name: 'Acute Stroke',
    category: 'neurological',
    description: 'Stroke protocol (RCP National Clinical Guideline)',
    icon: '🧠',
    color: 'bg-indigo-500',
    items: [
      {
        id: '1',
        title: 'CT head (non-contrast)',
        description: 'Within 1 hour of arrival',
        category: 'imaging',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Stroke team assessment',
        description: 'Urgent stroke team review for thrombolysis',
        category: 'consult',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'NIHSS score',
        description: 'Baseline stroke severity',
        category: 'other',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Swallow screen',
        description: 'Nil by mouth until completed',
        category: 'nursing',
        priority: 'high',
        timing: '4hr',
        isPreChecked: true,
      },
      {
        id: '5',
        title: 'FBC, U&Es, glucose, lipids, coagulation',
        description: 'Baseline bloods',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '6',
        title: 'ECG',
        description: 'Exclude AF',
        category: 'other',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '4-6 hours (acute phase)',
    clinicalGuideline: 'RCP Stroke Guidelines',
  },

  // 6. Pneumonia
  {
    id: 'pneumonia',
    name: 'Community-Acquired Pneumonia',
    category: 'respiratory',
    description: 'Pneumonia management (BTS Guidelines)',
    icon: '🫁',
    color: 'bg-teal-500',
    items: [
      {
        id: '1',
        title: 'Blood cultures',
        description: '2 sets before antibiotics if possible',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'IV antibiotics',
        description: 'Co-amoxiclav 1.2g + Clarithromycin 500mg',
        category: 'medication',
        priority: 'critical',
        timing: '4hr',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'CXR PA + lateral',
        description: 'Confirm diagnosis',
        category: 'imaging',
        priority: 'high',
        timing: '4hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'FBC, U&Es, CRP',
        description: 'Baseline bloods',
        category: 'lab',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
      {
        id: '5',
        title: 'CURB-65 score',
        description: 'Assess severity',
        category: 'other',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'Sputum culture',
        description: 'If productive cough',
        category: 'lab',
        priority: 'medium',
        timing: 'routine',
        isPreChecked: false,
      },
      {
        id: '7',
        title: 'Repeat CXR in 6 weeks',
        description: 'Follow-up to confirm resolution',
        category: 'imaging',
        priority: 'medium',
        timing: '24hr',
        isPreChecked: false,
        notes: 'Arrange as outpatient',
      },
    ],
    estimatedDuration: '4-6 hours',
    clinicalGuideline: 'BTS Pneumonia Guidelines',
  },

  // 7. AKI
  {
    id: 'aki',
    name: 'Acute Kidney Injury',
    category: 'renal',
    description: 'AKI investigation and management (NICE NG148)',
    icon: '🩺',
    color: 'bg-cyan-500',
    items: [
      {
        id: '1',
        title: 'U&Es (serial)',
        description: 'Baseline and repeat',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Urinalysis + MC&S',
        description: 'Exclude infection',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'Fluid balance chart',
        description: 'Strict input/output monitoring',
        category: 'nursing',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Review medications',
        description: 'Stop nephrotoxins (NSAIDs, ACEi, gentamicin)',
        category: 'medication',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '5',
        title: 'Renal ultrasound',
        description: 'Exclude obstruction',
        category: 'imaging',
        priority: 'high',
        timing: '24hr',
        isPreChecked: false,
      },
      {
        id: '6',
        title: 'FBC, CRP',
        description: 'Baseline bloods',
        category: 'lab',
        priority: 'medium',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '24-48 hours',
    clinicalGuideline: 'NICE NG148 - AKI',
  },

  // 8. GI Bleed
  {
    id: 'gi-bleed',
    name: 'Upper GI Bleed',
    category: 'gastrointestinal',
    description: 'Upper GI bleed management (NICE CG141)',
    icon: '🩸',
    color: 'bg-red-700',
    items: [
      {
        id: '1',
        title: 'FBC, U&Es, LFTs, coagulation',
        description: 'Baseline bloods',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Group & Save',
        description: 'Prepare for transfusion',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'Cross-match 2-4 units',
        description: 'If haemodynamically unstable',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: false,
        notes: 'Only if Hb <70 or unstable',
      },
      {
        id: '4',
        title: 'IV PPI (omeprazole 80mg)',
        description: 'Bolus then infusion',
        category: 'medication',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '5',
        title: 'Rockall score',
        description: 'Risk stratification',
        category: 'other',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'Gastroscopy',
        description: 'Urgent if haemodynamic instability',
        category: 'procedure',
        priority: 'critical',
        timing: '4hr',
        isPreChecked: true,
        notes: 'Contact gastro on-call',
      },
    ],
    estimatedDuration: '4-12 hours',
    clinicalGuideline: 'NICE CG141 - Upper GI Bleed',
  },
];

// Helper to get order set by ID
export function getOrderSetById(id: string): OrderSet | undefined {
  return ORDER_SETS.find((set) => set.id === id);
}

// Get order sets by category
export function getOrderSetsByCategory(category: string): OrderSet[] {
  return ORDER_SETS.filter((set) => set.category === category);
}
