/**
 * Order Set Templates
 *
 * Pre-built order sets for common clinical scenarios.
 * Each protocol includes verified evidence-based sources from
 * NICE, UpToDate, Medscape, and relevant professional societies.
 */

import type { OrderSet } from '@/types/orderSet';

export const ORDER_SETS: OrderSet[] = [
  // 1. Chest Pain / ACS
  {
    id: 'chest-pain-acs',
    name: 'Chest Pain / ACS',
    category: 'cardiac',
    description: 'Acute coronary syndrome workup and initial management',
    icon: '💔',
    color: 'bg-red-500',
    items: [
      {
        id: '1',
        title: '12-lead ECG',
        description: 'Obtain within 10 minutes of arrival. Repeat every 15-30 min if ongoing pain or dynamic changes. Look for ST elevation, ST depression, T-wave inversion, new LBBB.',
        category: 'other',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Compare with prior ECGs if available. Serial ECGs are critical for evolving STEMI.',
      },
      {
        id: '2',
        title: 'High-sensitivity troponin (0h)',
        description: 'Baseline hs-cTnT or hs-cTnI. Use ESC 0/1h or 0/3h rapid rule-out algorithm based on local assay.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'hs-cTnT <5 ng/L at 0h with low-risk features = rule out. >52 ng/L = rule in.',
      },
      {
        id: '3',
        title: 'High-sensitivity troponin (repeat)',
        description: 'Repeat at 1h (ESC 0/1h algorithm) or 3h (0/3h algorithm) depending on local protocol.',
        category: 'lab',
        priority: 'critical',
        timing: '4hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Aspirin 300mg STAT',
        description: 'Chew and swallow immediately unless true aspirin allergy or active bleeding. Give to all suspected ACS unless contraindicated.',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Contraindications: known allergy, active GI bleed. Do NOT delay for troponin result.',
      },
      {
        id: '5',
        title: 'FBC, U&Es, glucose, lipid profile, coagulation',
        description: 'Baseline bloods. Check renal function before contrast/angiography. Check Hb for bleeding risk.',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '6',
        title: 'Chest X-ray',
        description: 'PA erect. Exclude aortic dissection (widened mediastinum), pneumothorax, and pulmonary oedema. Should not delay reperfusion.',
        category: 'imaging',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
      {
        id: '7',
        title: 'Cardiology referral',
        description: 'Urgent if STEMI (primary PCI pathway). Same-day if NSTEMI with GRACE score >140 or ongoing ischaemia.',
        category: 'consult',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
        notes: 'STEMI: door-to-balloon target <90 min. Call cardiac cath lab immediately.',
      },
    ],
    estimatedDuration: '3-6 hours',
    clinicalGuideline: 'NICE CG95, ESC 2023 ACS Guidelines',
    sources: [
      {
        name: 'NICE CG95 — Chest Pain of Recent Onset',
        url: 'https://www.nice.org.uk/guidance/cg95',
        publisher: 'NICE',
      },
      {
        name: 'ACS: Diagnosis and Management — UpToDate Overview',
        url: 'https://www.uptodate.com/contents/overview-of-the-acute-management-of-non-st-elevation-acute-coronary-syndromes',
        publisher: 'UpToDate',
      },
      {
        name: 'Acute Coronary Syndrome Treatment & Management',
        url: 'https://emedicine.medscape.com/article/1910735-treatment',
        publisher: 'Medscape',
      },
      {
        name: 'ESC 2023 Guidelines for ACS Management',
        url: 'https://www.escardio.org/Guidelines/Clinical-Practice-Guidelines/Acute-Coronary-Syndromes',
        publisher: 'ESC',
      },
    ],
  },

  // 2. Sepsis Six
  {
    id: 'sepsis-six',
    name: 'Sepsis Six',
    category: 'infectious',
    description: 'Sepsis recognition and initial resuscitation bundle — complete within 1 hour',
    icon: '🦠',
    color: 'bg-purple-500',
    items: [
      {
        id: '1',
        title: 'High-flow oxygen',
        description: 'Target SpO2 94-98% (88-92% if COPD/CO2 retainer). Apply high-flow if SpO2 <94%. Monitor continuously.',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Blood cultures (2 sets)',
        description: 'Two sets from different sites BEFORE antibiotics. Each set = aerobic + anaerobic bottle. Do not delay antibiotics >45 min for cultures.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'If vascular access difficult, give antibiotics first — cultures are ideal but must not delay treatment.',
      },
      {
        id: '3',
        title: 'IV antibiotics within 1 hour',
        description: 'Broad-spectrum per local guidelines. Common: Piperacillin-tazobactam 4.5g IV or Meropenem 1g IV if penicillin allergy/ESBL risk.',
        category: 'medication',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Each hour delay in antibiotics increases mortality by 7.6% (Kumar 2006). Give within 1 hour of recognition.',
      },
      {
        id: '4',
        title: 'IV fluid resuscitation',
        description: '30 ml/kg crystalloid (typically 2L for 70kg adult) within first 3 hours if hypotensive or lactate ≥4. Give 500ml bolus and reassess.',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Use balanced crystalloid (Hartmann/Plasmalyte) preferred over 0.9% NaCl. Reassess after each 500ml.',
      },
      {
        id: '5',
        title: 'Serum lactate',
        description: 'VBG or ABG lactate. If ≥2 mmol/L, repeat in 2-4 hours. Lactate ≥4 = septic shock until proven otherwise.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'Urine output monitoring',
        description: 'Insert urinary catheter if output unknown or suspected low. Target ≥0.5 ml/kg/hr. Strict fluid balance chart.',
        category: 'nursing',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '7',
        title: 'FBC, U&Es, CRP, LFTs, coagulation',
        description: 'Baseline organ function assessment. Check for DIC (platelets, fibrinogen, D-dimer if coagulopathy suspected).',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '8',
        title: 'Chest X-ray + source identification',
        description: 'CXR to exclude pneumonia. Consider urine dip, wound swab, LP if meningism, CT abdomen if intra-abdominal source suspected.',
        category: 'imaging',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '1-2 hours (bundle completion)',
    clinicalGuideline: 'Surviving Sepsis Campaign 2021',
    sources: [
      {
        name: 'NICE NG51 — Sepsis: Recognition, Diagnosis and Early Management',
        url: 'https://www.nice.org.uk/guidance/ng51',
        publisher: 'NICE',
      },
      {
        name: 'Surviving Sepsis Campaign: 2021 International Guidelines',
        url: 'https://www.sccm.org/SurvivingSepsisCampaign/Guidelines/Adult-Patients',
        publisher: 'SSC',
      },
      {
        name: 'Sepsis Empiric Therapy — UpToDate',
        url: 'https://www.uptodate.com/contents/evaluation-and-management-of-suspected-sepsis-and-septic-shock-in-adults',
        publisher: 'UpToDate',
      },
      {
        name: 'Sepsis Clinical Presentation and Workup',
        url: 'https://emedicine.medscape.com/article/234587-workup',
        publisher: 'Medscape',
      },
    ],
  },

  // 3. DKA
  {
    id: 'dka-protocol',
    name: 'DKA Protocol',
    category: 'metabolic',
    description: 'Diabetic ketoacidosis management — IV fluids, fixed-rate insulin, K+ monitoring',
    icon: '💉',
    color: 'bg-orange-500',
    items: [
      {
        id: '1',
        title: 'Venous blood gas',
        description: 'Confirm DKA: pH <7.3, bicarbonate <15 mmol/L, blood ketones >3 mmol/L or heavy ketonuria (2+). Classify severity.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Mild: pH 7.25-7.30. Moderate: pH 7.0-7.24. Severe: pH <7.0. Severe = HDU/ICU referral.',
      },
      {
        id: '2',
        title: 'Capillary blood glucose + ketones',
        description: 'Baseline BM and blood ketone measurement. Hourly monitoring thereafter.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'IV 0.9% NaCl fluid resuscitation',
        description: '1L over 1h, then 1L over 2h, then 1L over 2h, then 1L over 4h, then 1L over 4h. Adjust if elderly/cardiac failure.',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Switch to 10% dextrose when glucose <14 mmol/L (continue insulin infusion). Total deficit typically 5-8L.',
      },
      {
        id: '4',
        title: 'Fixed-rate insulin infusion (FRII)',
        description: '0.1 units/kg/hr IV Actrapid/Humulin S. Continue long-acting basal insulin at usual dose and time.',
        category: 'medication',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Target: ketones fall ≥0.5 mmol/L/hr, glucose fall 3 mmol/L/hr, bicarb rise 3 mmol/L/hr. If not achieving targets, increase rate by 1 unit/hr.',
      },
      {
        id: '5',
        title: 'Hourly BM, ketones, fluid balance',
        description: 'Hourly capillary glucose and blood ketones. Strict fluid balance chart. VBG every 2h until pH >7.3.',
        category: 'nursing',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'U&Es with potassium (2-hourly)',
        description: 'K+ replacement essential: Add 40mmol KCl/L if K+ 3.5-5.5. Hold if K+ >5.5. If K+ <3.5, senior review + aggressive replacement.',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Insulin drives K+ intracellularly. Hypokalaemia is the main cause of death in DKA. Check K+ before starting insulin.',
      },
      {
        id: '7',
        title: 'ECG',
        description: 'Baseline ECG to assess for hyperkalaemia (tall T waves, wide QRS) or cardiac ischaemia. Repeat if K+ abnormal.',
        category: 'other',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '24+ hours',
    clinicalGuideline: 'JBDS-IP 2023 DKA Guideline',
    sources: [
      {
        name: 'JBDS-IP Guideline for Management of DKA in Adults (2023)',
        url: 'https://abcd.care/jbds-guidelines',
        publisher: 'JBDS',
      },
      {
        name: 'Diabetic Ketoacidosis: Evaluation and Treatment — UpToDate',
        url: 'https://www.uptodate.com/contents/diabetic-ketoacidosis-and-hyperosmolar-hyperglycemic-state-in-adults-treatment',
        publisher: 'UpToDate',
      },
      {
        name: 'Diabetic Ketoacidosis Treatment & Management',
        url: 'https://emedicine.medscape.com/article/118361-treatment',
        publisher: 'Medscape',
      },
      {
        name: 'NICE NG17 — Type 1 Diabetes (DKA Management)',
        url: 'https://www.nice.org.uk/guidance/ng17',
        publisher: 'NICE',
      },
    ],
  },

  // 4. Hyperkalemia
  {
    id: 'hyperkalemia',
    name: 'Hyperkalemia',
    category: 'metabolic',
    description: 'Emergency hyperkalaemia management — cardiac protection, shift, elimination',
    icon: '⚡',
    color: 'bg-yellow-600',
    items: [
      {
        id: '1',
        title: '12-lead ECG',
        description: 'Assess for hyperkalaemia changes: tall peaked T waves (>5.5), PR prolongation (>6.0), loss of P waves, wide QRS (>6.5), sine wave (>7.0).',
        category: 'other',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'ECG changes do not always correlate with K+ level. Treat the patient, not the number. Any ECG change = give calcium.',
      },
      {
        id: '2',
        title: 'Calcium gluconate 10% IV (cardiac protection)',
        description: '30ml of 10% calcium gluconate IV over 5-10 minutes. Repeat ECG after 5 min. Can repeat x1 if ECG changes persist.',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Stabilises myocardium but does NOT lower K+. Effect lasts 30-60 min. Give via large-bore cannula — extravasation causes tissue necrosis.',
      },
      {
        id: '3',
        title: 'Insulin-dextrose (shift K+ intracellularly)',
        description: '10 units Actrapid in 25ml 50% dextrose IV over 15-30 min. Or: 10 units in 250ml 10% glucose over 30 min.',
        category: 'medication',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Lowers K+ by 0.5-1.2 mmol/L within 15-30 min. Duration 4-6h. Check BM hourly for 6h — hypoglycaemia risk 15-30%.',
      },
      {
        id: '4',
        title: 'Salbutamol nebuliser 10-20mg',
        description: '10-20mg nebulised salbutamol (2.5-5mg = usual asthma dose, so this is 4-8x higher). Can combine with insulin-dextrose.',
        category: 'medication',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: false,
        notes: 'Lowers K+ by 0.5-1.0 mmol/L. Additive effect with insulin-dextrose. Use with caution if tachyarrhythmia.',
      },
      {
        id: '5',
        title: 'Recheck K+ in 1-2 hours',
        description: 'Repeat venous K+ to assess response. If still elevated, consider repeat insulin-dextrose or renal replacement.',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '6',
        title: 'Stop nephrotoxic / K+-sparing drugs',
        description: 'Review and stop: ACE inhibitors, ARBs, spironolactone/eplerenone, amiloride, NSAIDs, trimethoprim. Review potassium-containing IV fluids.',
        category: 'medication',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
    ],
    estimatedDuration: '2-4 hours',
    clinicalGuideline: 'Renal Association / Resuscitation Council UK',
    sources: [
      {
        name: 'UK Renal Association: Treatment of Acute Hyperkalaemia in Adults',
        url: 'https://ukkidney.org/sites/renal.org/files/RENAL%20ASSOCIATION%20HYPERKALAEMIA%20GUIDELINE%20-%20JULY%202023.pdf',
        publisher: 'Resuscitation Council UK',
      },
      {
        name: 'Treatment and Prevention of Hyperkalemia in Adults — UpToDate',
        url: 'https://www.uptodate.com/contents/treatment-and-prevention-of-hyperkalemia-in-adults',
        publisher: 'UpToDate',
      },
      {
        name: 'Hyperkalemia Treatment & Management',
        url: 'https://emedicine.medscape.com/article/240903-treatment',
        publisher: 'Medscape',
      },
    ],
  },

  // 5. Stroke / CVA
  {
    id: 'stroke',
    name: 'Acute Stroke',
    category: 'neurological',
    description: 'Stroke code — rapid assessment, imaging, thrombolysis/thrombectomy pathway',
    icon: '🧠',
    color: 'bg-indigo-500',
    items: [
      {
        id: '1',
        title: 'CT head (non-contrast) URGENT',
        description: 'Within 1 hour of arrival (immediately if thrombolysis candidate). Exclude haemorrhage. CT angiography if LVO thrombectomy considered.',
        category: 'imaging',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Do NOT delay for blood results unless on anticoagulants. Door-to-CT target <25 min.',
      },
      {
        id: '2',
        title: 'Stroke team / thrombolysis assessment',
        description: 'Urgent stroke team review. Alteplase eligible if ischaemic stroke <4.5h onset (or last known well). Thrombectomy eligible up to 24h with favourable imaging.',
        category: 'consult',
        priority: 'critical',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Door-to-needle target <60 min. Alteplase 0.9mg/kg (max 90mg): 10% bolus, rest over 60 min.',
      },
      {
        id: '3',
        title: 'NIHSS score',
        description: 'National Institutes of Health Stroke Scale — baseline stroke severity. Repeat at 24h and discharge. Score >6 = consider thrombectomy referral.',
        category: 'other',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Swallow screen (before oral intake)',
        description: 'Bedside swallow screen using validated tool (e.g., GUSS). If fails or reduced consciousness: NBM and refer to SLT. Aspiration pneumonia risk.',
        category: 'nursing',
        priority: 'high',
        timing: '4hr',
        isPreChecked: true,
        notes: 'Keep NBM until swallow screen completed. IV fluids for hydration.',
      },
      {
        id: '5',
        title: 'FBC, U&Es, glucose, lipids, coagulation, HbA1c',
        description: 'Baseline bloods. Glucose >11 mmol/L associated with worse outcomes — treat with insulin. Check INR if on warfarin (must be <1.7 for thrombolysis).',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: false,
      },
      {
        id: '6',
        title: 'ECG',
        description: 'Exclude atrial fibrillation (most common cardioembolic cause). Look for acute MI (concurrent stroke + MI). Telemetry for 24-72h.',
        category: 'other',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '4-6 hours (acute phase)',
    clinicalGuideline: 'RCP National Clinical Guideline for Stroke 2023',
    sources: [
      {
        name: 'NICE NG128 — Stroke and TIA in Over 16s',
        url: 'https://www.nice.org.uk/guidance/ng128',
        publisher: 'NICE',
      },
      {
        name: 'RCP National Clinical Guideline for Stroke (2023)',
        url: 'https://www.strokeguideline.org',
        publisher: 'RCP',
      },
      {
        name: 'Initial Assessment and Management of Acute Stroke — UpToDate',
        url: 'https://www.uptodate.com/contents/initial-assessment-and-management-of-acute-stroke',
        publisher: 'UpToDate',
      },
      {
        name: 'Ischemic Stroke Treatment & Management',
        url: 'https://emedicine.medscape.com/article/1916852-treatment',
        publisher: 'Medscape',
      },
    ],
  },

  // 6. Pneumonia
  {
    id: 'pneumonia',
    name: 'Community-Acquired Pneumonia',
    category: 'respiratory',
    description: 'CAP severity assessment, empiric antibiotics, and monitoring',
    icon: '🫁',
    color: 'bg-teal-500',
    items: [
      {
        id: '1',
        title: 'Blood cultures (2 sets)',
        description: '2 sets before antibiotics if moderate-severe (CURB-65 ≥2). Not required for mild CAP treated outpatient.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '2',
        title: 'Empiric IV antibiotics',
        description: 'Mild (CURB-65 0-1): Amoxicillin 500mg TDS PO. Moderate (CURB-65 2): Amoxicillin + Clarithromycin. Severe (CURB-65 3-5): Co-amoxiclav 1.2g IV + Clarithromycin 500mg IV.',
        category: 'medication',
        priority: 'critical',
        timing: '4hr',
        isPreChecked: true,
        notes: 'Penicillin allergy: use Levofloxacin 500mg IV/PO. Add Clarithromycin if atypical cover needed. Review at 48h for IV-to-oral switch.',
      },
      {
        id: '3',
        title: 'Chest X-ray (PA)',
        description: 'Confirm consolidation pattern. Lobar, bronchopneumonia, or interstitial pattern. Bilateral = consider atypical, PCP, or ARDS.',
        category: 'imaging',
        priority: 'high',
        timing: '4hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'FBC, U&Es, CRP, LFTs',
        description: 'CRP >100 supports bacterial pneumonia. Check urea for CURB-65 scoring. Repeat CRP at 48-72h to assess response.',
        category: 'lab',
        priority: 'high',
        timing: '4hr',
        isPreChecked: false,
      },
      {
        id: '5',
        title: 'CURB-65 severity score',
        description: 'Confusion, Urea >7, RR ≥30, BP systolic <90 or diastolic ≤60, Age ≥65. Score 0-1: home. 2: consider admission. 3-5: severe — HDU/ICU.',
        category: 'other',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: true,
        notes: '30-day mortality: Score 0 = 0.6%, 1 = 2.7%, 2 = 6.8%, 3 = 14%, 4 = 27.8%, 5 = 27.8%.',
      },
      {
        id: '6',
        title: 'Sputum culture (if productive)',
        description: 'Send before antibiotics if possible. Gram stain + culture + sensitivity. Consider Legionella urinary antigen and Pneumococcal antigen if severe.',
        category: 'lab',
        priority: 'medium',
        timing: 'routine',
        isPreChecked: false,
      },
      {
        id: '7',
        title: 'Follow-up CXR at 6 weeks',
        description: 'Arrange outpatient CXR to confirm radiological resolution. Essential to exclude underlying malignancy, especially in smokers >50y.',
        category: 'imaging',
        priority: 'medium',
        timing: '24hr',
        isPreChecked: false,
        notes: 'Document in discharge summary. Non-resolution at 6 weeks → CT chest + respiratory referral.',
      },
    ],
    estimatedDuration: '4-6 hours',
    clinicalGuideline: 'BTS CAP Guidelines 2009 + NICE CG191',
    sources: [
      {
        name: 'NICE CG191 — Pneumonia in Adults: Diagnosis and Management',
        url: 'https://www.nice.org.uk/guidance/cg191',
        publisher: 'NICE',
      },
      {
        name: 'BTS Guidelines for Management of CAP in Adults',
        url: 'https://www.brit-thoracic.org.uk/quality-improvement/guidelines/pneumonia-adults/',
        publisher: 'BTS',
      },
      {
        name: 'Community-Acquired Pneumonia in Adults: Treatment — UpToDate',
        url: 'https://www.uptodate.com/contents/treatment-of-community-acquired-pneumonia-in-adults-who-require-hospitalization',
        publisher: 'UpToDate',
      },
      {
        name: 'Community-Acquired Pneumonia Empiric Therapy',
        url: 'https://emedicine.medscape.com/article/234240-treatment',
        publisher: 'Medscape',
      },
    ],
  },

  // 7. AKI
  {
    id: 'aki',
    name: 'Acute Kidney Injury',
    category: 'renal',
    description: 'AKI investigation, staging (KDIGO), and initial management',
    icon: '🩺',
    color: 'bg-cyan-500',
    items: [
      {
        id: '1',
        title: 'U&Es (serial monitoring)',
        description: 'Baseline and repeat. KDIGO staging: Stage 1: Cr 1.5-1.9x baseline or ≥26.5 μmol/L increase in 48h. Stage 2: 2-2.9x. Stage 3: ≥3x or Cr ≥354 or RRT initiated.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Compare with baseline creatinine. No baseline available? Estimate from MDRD assuming eGFR 75 ml/min.',
      },
      {
        id: '2',
        title: 'Urinalysis + urine MC&S',
        description: 'Dipstick for blood + protein (intrinsic renal disease). Send MSU for culture. Protein:creatinine ratio if significant proteinuria.',
        category: 'lab',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
        notes: 'Blood + protein on dip = consider glomerulonephritis → urgent nephrology referral.',
      },
      {
        id: '3',
        title: 'Strict fluid balance monitoring',
        description: 'Catheterise if unable to monitor output. Target UO ≥0.5 ml/kg/hr. Hourly fluid balance chart.',
        category: 'nursing',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
      },
      {
        id: '4',
        title: 'Review and stop nephrotoxic medications',
        description: 'Stop: NSAIDs, ACE inhibitors/ARBs, aminoglycosides, metformin, lithium. Adjust doses of renally-cleared drugs. Review IV contrast exposure.',
        category: 'medication',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
        notes: '"DAMN" mnemonic: Diuretics, ACEi/ARBs, Metformin, NSAIDs — stop all in AKI.',
      },
      {
        id: '5',
        title: 'Renal tract ultrasound',
        description: 'Urgent if suspected obstruction (anuria, palpable bladder, known pelvic/abdominal malignancy, single kidney). Within 24h otherwise.',
        category: 'imaging',
        priority: 'high',
        timing: '24hr',
        isPreChecked: false,
        notes: 'Hydronephrosis = obstruction → urology referral for nephrostomy/stent.',
      },
      {
        id: '6',
        title: 'FBC, CRP, LDH, CK, blood film',
        description: 'Investigate cause. CK for rhabdomyolysis. Blood film + LDH for HUS/TTP. CRP for infection-related AKI.',
        category: 'lab',
        priority: 'medium',
        timing: '4hr',
        isPreChecked: false,
      },
    ],
    estimatedDuration: '24-48 hours',
    clinicalGuideline: 'NICE NG148 — AKI',
    sources: [
      {
        name: 'NICE NG148 — Acute Kidney Injury: Prevention, Detection and Management',
        url: 'https://www.nice.org.uk/guidance/ng148',
        publisher: 'NICE',
      },
      {
        name: 'KDIGO Clinical Practice Guideline for AKI',
        url: 'https://kdigo.org/guidelines/acute-kidney-injury/',
        publisher: 'NICE',
      },
      {
        name: 'Overview of the Management of AKI in Adults — UpToDate',
        url: 'https://www.uptodate.com/contents/overview-of-the-management-of-acute-kidney-injury-in-adults',
        publisher: 'UpToDate',
      },
      {
        name: 'Acute Kidney Injury Treatment & Management',
        url: 'https://emedicine.medscape.com/article/243492-treatment',
        publisher: 'Medscape',
      },
    ],
  },

  // 8. GI Bleed
  {
    id: 'gi-bleed',
    name: 'Upper GI Bleed',
    category: 'gastrointestinal',
    description: 'Upper GI bleed resuscitation, risk stratification, and urgent endoscopy pathway',
    icon: '🩸',
    color: 'bg-red-700',
    items: [
      {
        id: '1',
        title: 'FBC, U&Es, LFTs, coagulation screen',
        description: 'Baseline: Hb (may be normal initially in acute bleed), platelets, INR/PT, urea (raised urea:creatinine ratio suggests UGIB).',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Hb may not reflect true blood loss for 6-24h (haemodilution). Urea >10 with normal creatinine = upper GI source.',
      },
      {
        id: '2',
        title: 'Group & Save + crossmatch',
        description: 'Group & Save for all. Crossmatch 2-4 units if haemodynamically unstable, Hb <70 g/L, or active visible bleeding.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: true,
      },
      {
        id: '3',
        title: 'Transfusion (if indicated)',
        description: 'Transfuse if Hb <70 g/L (restrictive strategy). Target Hb 70-90 g/L. Higher threshold (80 g/L) if ACS or haemodynamically unstable.',
        category: 'lab',
        priority: 'critical',
        timing: 'STAT',
        isPreChecked: false,
        notes: 'Over-transfusion in variceal bleed worsens portal pressure and rebleeding risk. Use O-neg if crossmatch not ready and patient unstable.',
      },
      {
        id: '4',
        title: 'IV PPI (omeprazole 80mg bolus)',
        description: 'Omeprazole 80mg IV bolus, then 40mg BD IV or 8mg/hr infusion. Switch to oral PPI after endoscopy confirms non-variceal source.',
        category: 'medication',
        priority: 'high',
        timing: '1hr',
        isPreChecked: true,
        notes: 'If variceal bleed suspected (known liver disease/portal hypertension): give Terlipressin 2mg IV + prophylactic antibiotics (Ceftriaxone 1g IV).',
      },
      {
        id: '5',
        title: 'Glasgow-Blatchford Score (GBS)',
        description: 'Pre-endoscopy risk stratification. Score 0 = safe for outpatient management. Score ≥6 = high risk, urgent endoscopy.',
        category: 'other',
        priority: 'high',
        timing: 'STAT',
        isPreChecked: true,
        notes: 'Uses: urea, Hb, systolic BP, pulse, melaena, syncope, hepatic disease, cardiac failure. GBS >0 = admit.',
      },
      {
        id: '6',
        title: 'Urgent OGD (oesophagogastroduodenoscopy)',
        description: 'Within 24h for all admitted UGIB. Within 12h if haemodynamically unstable despite resuscitation. Within 2h if massive/variceal bleed.',
        category: 'procedure',
        priority: 'critical',
        timing: '4hr',
        isPreChecked: true,
        notes: 'Contact gastro on-call. Erythromycin 250mg IV 30-90 min pre-OGD improves visualisation (prokinetic).',
      },
    ],
    estimatedDuration: '4-12 hours',
    clinicalGuideline: 'NICE CG141 — Upper GI Bleed',
    sources: [
      {
        name: 'NICE CG141 — Acute Upper GI Bleeding in Over 16s',
        url: 'https://www.nice.org.uk/guidance/cg141',
        publisher: 'NICE',
      },
      {
        name: 'Approach to Acute Upper GI Bleeding in Adults — UpToDate',
        url: 'https://www.uptodate.com/contents/approach-to-acute-upper-gastrointestinal-bleeding-in-adults',
        publisher: 'UpToDate',
      },
      {
        name: 'Upper Gastrointestinal Bleeding Treatment & Management',
        url: 'https://emedicine.medscape.com/article/187857-treatment',
        publisher: 'Medscape',
      },
      {
        name: 'BSG Guidelines on Management of Variceal Haemorrhage',
        url: 'https://www.bsg.org.uk/clinical-resource/uk-guidelines-on-the-management-of-variceal-haemorrhage-in-cirrhotic-patients/',
        publisher: 'BTS',
      },
    ],
  },
];

// Helper to get order set by ID
export function getOrderSetById(id: string): OrderSet | undefined {
  return ORDER_SETS.find((set) => set.id === id);
}

// Get order sets by category
export function getOrderSetsByCategory(category: string): OrderSet[] {
  return ORDER_SETS.filter((set) => set.category === category);
}
